### ISSUE TITLE
Fix encoding representation

### ISSUE THREAD

**Issue by skrah** [libdynd/libdynd#1093]
>>> ndt.type("char['ucs2']")
 ndt.type('char['ucs2']')

In the representation, the encoding should use different quotes from the outer quotes.  Alternatively, it would be nice to get rid of the quotes altogether and make the encodings keywords.

**Comment by insertinterestingnamehere** [comment]
I think the long-term plan is to only provide utf-8 and make it the default, but make user-defined string encodings possible in-case someone else ever wants to take the time to whatever other encodings they need as a separate package. With that in mind, we really need to avoid making the encodings into keywords. Making the outer quotes different from the inner ones seems like a good solution.

**Comment by mwiebe** [comment]
Do we want multiple different `char` types? For `char` I was imagining storage as just one uint32, a single code point.

**Comment by skrah** [comment]
PEP-3118 had 'a' for ascii chars, 'u' for ucs2 and 'w' for utf32.  It was never really implemented and many of the unicode experts questioned the usefulness.

The advantage of only supporting char=uint32 would be that it's just a scalar (additionally, anything that makes the grammar smaller is good IMHO).

**Comment by insertinterestingnamehere** [comment]
Good points. We probably don't need the string parameter there. For some reason I was thinking this applied to strings, which aren't currently parameterized at all. It'd be nice if we still allowed string parameters for types, but I see no reason for `char` to be parameterized in this way. Given that strings don't use that functionality right now, we don't necessarily even need to keep that functionality at all right now if it's too much of a pain.

**Comment by skrah** [comment]
Fixed strings still use the encoding, and it seems to work quite well:

```
>>> nd.array(["abc\U00010ffff", "x"], type="2 * fixed_string[6, 'utf16']")
nd.array(["abc\U00010ffff",              "x"],
         type="2 * fixed_string[6,'utf16']")
```

String parameters in general aren't that bad, I just dislike to type them inside another string (like above).

**Comment by skrah** [comment]
I just checked and using NAME_LOWER in the datashape grammar for type constructor arguments is conflict free.  So I think user defined arguments would be unaffected by dropping the quotes around the encoding.

**Comment by mwiebe** [comment]
That would conflict with general pluggability of the parser, wouldn't it? If someone adds a type which adopts the name 'utf16' (or other context where we allow dropping the quotes), how do we distinguish? Should we maybe make the parsing context-sensitive, and add type constructor signatures to the parsing?

**Comment by skrah** [comment]
Yes, you're right:  I checked the current libdynd parser, where ```type_arg``` is commented out.  Adding NAME_LOWER to ```type_arg``` would cause a conflict.

Right now, I probably would not make the parsing context sensitive.

**Comment by skrah** [comment]
This is fixed by https://github.com/libdynd/dynd-python/pull/633 .

@izaid There seems to be moderate enthusiasm for making ```char``` a scalar (UTF-32). What do you think?

**Comment by izaid** [comment]
@skrah I'm okay with the consensus on that, but it may have knock-on effects.
