### ISSUE TITLE
bytes_type: data_alignment/target_alignment

### ISSUE THREAD

**Issue by skrah** [libdynd/libdynd#1095]
In the bytes[] type constructor "align" refers to the target alignment:

```
>>> t = ndt.type("bytes[align=16]")
>>> t.target_alignment
16
>>> t.data_alignment
8
```

In fixed_bytes, it refers to the data_alignment:

```
>>> t = ndt.type("fixed_bytes[1600, align=16]")
>>> t.data_alignment
16
```

Additionally, in bytes[] the target_alignment can be smaller than the data_alignment:

```
>>> t = ndt.type("bytes[align=2]")
>>> t.data_alignment
8
>>> t.target_alignment
2
```

**Comment by mwiebe** [comment]
In all cases, the "align" refers to the bytes being stored. This is confusing though, I agree.

**Comment by izaid** [comment]
This is the same issue as strings. Variable-sized bytes no longer have an alignment, whereas fixed bytes too.

**Comment by skrah** [comment]
I think I need to understand this better. Is this explanation correct (the
numbers below reflect the current state of the source)?


fixed_bytes[32, align=8]
------------------------

  data_size: 32      (the size of the payload)
  data_alignment: 8  (the alignment of the payload)

So an array[3] of fixed bytes would look like:

         32 bytes        32 bytes        32 bytes
    |---------------|---------------|---------------|

The bytes are embedded in the array and the whole array has an alignment of 8.


bytes[align=2]
--------------

  data_size: 16         (the size of the bytes object)
  data_alignment: 8     (the alignment of the bytes object)
  target alignment: 2  (the alignment of the payload held by the bytes object)

So an array[3] of bytes is much like ```char *array[3]```, but the objects
are embedded in the array(?!):

```
    -
  o |
  b | -> "payload, aligned at 2"
  j |
    -
  o |
  b | -> "payload, aligned at 2"
  j |
    -
  o |
  b | -> "payload, aligned at 2"
  j |
    -
```

The ```data size``` part is confusing here, I'd expect pointers to be embedded in the array.

As I understand @izaid, ```data_size``` should be 0 and the ```align``` keyword and ```target_alignment``` should be removed.

**Comment by mwiebe** [comment]
That is correct. `data_size` is always the storage size of an instance of the type, which is 16 because it contains a pointer and a size. Making `data_size` 0 would break the current data model of DyND.

**Comment by skrah** [comment]
Thanks!  If pointer+size are one array element, it all makes sense.
