### ISSUE TITLE
template-based callables should template on types and not on type ids

### ISSUE THREAD

**Issue by insertinterestingnamehere** [libdynd/libdynd#1197]
This is an issue where we can continue some internal discussion we've had going for some time.

Currently, many of the callables that DyND exports are built from templates that use known compile-time type ids. This complicates some of the templating code. It also restricts the templates we define so that they can only be used with types that have type ids known at compile time.

It'd be a lot better if most templates were defined in terms of either the concrete types on which they operate (like float or int), or, the type classes defined in the dynd/types folder (e.g. https://github.com/libdynd/libdynd/blob/master/include/dynd/types/fixed_dim_type.hpp). We could then use a separate template to get the corresponding type ids when they are needed. One possible benefit of this would be that, once a type has been registered as a user-defined type and has defined a template that can be used to access its type id, c++ types that have corresponding DyND types could use the templates we've already written to register themselves for arithmetic operations, etc.

**Comment by izaid** [comment]
Closing, because we achieved this!

**Comment by insertinterestingnamehere** [comment]
This is fantastic! Thanks!
