### ISSUE TITLE
Implicit Fallthrough in Substitute TypeVars

### ISSUE THREAD

**Issue by Alexhuszagh** [libdynd/libdynd#1323]
In `substitute_typevars.cpp`, using GCC-7.1.1, there is an implicit fallthrough in the `ndt::detail::internal_substitute` for the case of a `typevar_constructed_id`. 

The original code looks something like this:

```cpp
  case typevar_constructed_id: {
    map<std::string, ndt::type>::const_iterator it =
        typevars.find(pattern.extended<typevar_constructed_type>()->get_name());
    if (it->second.get_id() == void_id) {
      return substitute(pattern.extended<typevar_constructed_type>()->get_arg(), typevars, concrete);
    }
#ifdef DYND_CUDA
    if (it->second.get_id() == cuda_device_id) {
      return ndt::make_cuda_device(
          substitute(pattern.extended<typevar_constructed_type>()->get_arg(), typevars, concrete));
    }
#endif
// implicit fallthrough here...
  }
```

Although the implicit fall-through is logically unreachable, the compiler does not know this. Changing the above code to the following prevents any implicit fallthroughts:

```cpp
  case typevar_constructed_id: {
    map<std::string, ndt::type>::const_iterator it =
        typevars.find(pattern.extended<typevar_constructed_type>()->get_name());
    if (it->second.get_id() == void_id) {
      return substitute(pattern.extended<typevar_constructed_type>()->get_arg(), typevars, concrete);
    }
#ifdef DYND_CUDA
    if (it->second.get_id() == cuda_device_id) {
      return ndt::make_cuda_device(
          substitute(pattern.extended<typevar_constructed_type>()->get_arg(), typevars, concrete));
    }
#endif
    stringstream ss;
    ss << "No constructed id for dynd type var " << pattern << " was available";
    throw invalid_argument(ss.str());
  }
```

**Comment by insertinterestingnamehere** [comment]
Right, there are a few warnings I need to go back and finish cleaning up for gcc 7. You beat me to this one. Feel free to include this in a bugfix PR.

**Comment by insertinterestingnamehere** [comment]
Hrm. That is a remarkably pedantic warning. After looking at that a bit more, I think sticking a break statement at the end of the cases in the switch statement is the right way to do it, but it'd be nice if @izaid or @mwiebe could confirm that. I haven't done much with the code for typevars.

**Comment by Alexhuszagh** [comment]
A break will lead to a "control reaches the end of a non-void function". I believe this is non-reachable code in all practical applications, however, the compiler does not know this.

**Comment by insertinterestingnamehere** [comment]
Okay, I've looked through it some more. Yes, that code should never be reached. AFAICT it's a remnant from the (currently unsupported) cuda configuration. The error here is fine.
