### ISSUE TITLE
Issues compiling /testing with VS 2012

### ISSUE THREAD

**Issue by cournape** [libdynd/libdynd#271]
Hi Mark,

I tried building dynd with vs 2012 (amd64), but got a few issues (tag v0.6.6)

* arrfuncs_registry.cpp does not build because VS 2012 (compiler version 17.*) does not have those functions according to MSDN. I incremented the version check macro to 1800, and everything built
* 3 test failed while running the test suite:

```
 FAILED  ] ShapeTools.MultiStridesToAxisPerm_TwoOps (0 ms)
[----------] 3 tests from ShapeTools (0 ms total)

[----------] Global test environment tear-down
[==========] 545 tests from 130 test cases ran. (355 ms total)
[  PASSED  ] 542 tests.
[  FAILED  ] 3 tests, listed below:
[  FAILED  ] Array.ConstructorMemoryLayouts
[  FAILED  ] ShapeTools.MultiStridesToAxisPerm_OneOp
[  FAILED  ] ShapeTools.MultiStridesToAxisPerm_TwoOps

 3 FAILED TESTS
```

The actual output is fairly large (~ 1.1 MB), let me know if you need it.

Are you still interested in supporting vs 2012, or should I just use a more recent one (docs should be updated in that case)

**Comment by izaid** [comment]
Hi David,

We recently updated libdynd to use C++11, and thus do require Visual Studio 2013. This is mentioned in some of the docs (see BUILD.md), but sorry you couldn't find it easily!

**Comment by cournape** [comment]
@izaid it was not mentioned in the tarball, but I see indeed the requirement updated from 2010 to 2013 in master.

Quick question: I suspect you need to build dynd_python w/ the same compiler. Is that how you build it even for python 2.x ?

**Comment by izaid** [comment]
Ok, cool, thanks for letting us know about the tarball.

Yes, I believe we typically build dynd_python with the same compiler. I don't use Windows, so @mwiebe can jump in if I've got something wrong.

**Comment by cournape** [comment]
I can confirm the 3 tests now pass with VS 2013. Aren't compiler bugs fun :)

**Comment by mwiebe** [comment]
@cournape we do use the same compiler for building the Python bindings, and even though it's not something recommended by Microsoft, haven't run into any difficulties doing so. Thanks for trying it out!
