### ISSUE TITLE
Build Error with clang on FreeBSD 10.1

### ISSUE THREAD

**Issue by insertinterestingnamehere** [libdynd/libdynd#408]
Though not technically supported, I use a FreeBSD box to lint for possible issues. It's particularly useful because FreeBSD gives me a free platform where clang/libc++ are the default. Recent versions of master have been showing the following build error:

/usr/local/bin/clang++36    -O3 -std=c++11 -fomit-frame-pointer -fstrict-aliasing -Wall -Wextra -Werror -Wno-missing-field-initializers -fPIC -ferror-limit=20 -O3 -DNDEBUG -I/usr/home/me/libdynd/thirdparty/datetime/include -I/usr/home/me/libdynd/include -I/usr/home/me/libdynd/thirdparty/utf8/source -I/usr/home/me/libdynd/build/include -o CMakeFiles/libdynd_OBJ.dir/src/dynd/func/arithmetic.cpp.o -c /usr/home/me/libdynd/src/dynd/func/arithmetic.cpp                                                                                                                                          
In file included from /usr/home/me/libdynd/src/dynd/func/arithmetic.cpp:6:                                                                         
In file included from /usr/home/me/libdynd/include/dynd/func/arithmetic.hpp:6:                                                                     
In file included from /usr/home/me/libdynd/include/dynd/func/arrfunc.hpp:10:                                                                       
In file included from /usr/home/me/libdynd/include/dynd/config.hpp:142:                                                                            
/usr/home/me/libdynd/include/dynd/type_sequence.hpp:377:22: error: implicit instantiation of undefined template 'dynd::detail::get_impl<0>'        
    typedef typename get_impl<I - 1, A...>::result_type result_type;                                                                               
                     ^
/usr/home/me/libdynd/include/dynd/type_sequence.hpp:386:18: note: in instantiation of template class 'dynd::detail::get_impl<1,
      std::__1::pair<const std::__1::pair<dynd::type_id_t, dynd::type_id_t>, dynd::nd::arrfunc> &>' requested here
typename detail::get_impl<I, A...>::result_type get(A &&... a)
                 ^
/usr/include/c++/v1/utility:350:86: note: while substituting deduced template arguments into function template 'get' [with I = 1, A =
      <std::__1::pair<const std::__1::pair<dynd::type_id_t, dynd::type_id_t>, dynd::nd::arrfunc> &>]
                                   typename __make_tuple_types<_Tuple>::type>::type>(get<1>(__p)))
                                                                                     ^
/usr/home/me/libdynd/include/dynd/func/arithmetic.hpp:65:76: note: in instantiation of function template specialization
      'std::__1::pair<std::__1::pair<dynd::type_id_t, dynd::type_id_t>, dynd::nd::arrfunc>::pair<std::__1::pair<const
      std::__1::pair<dynd::type_id_t, dynd::type_id_t>, dynd::nd::arrfunc> &, void>' requested here
      for (const std::pair<std::pair<type_id_t, type_id_t>, arrfunc> &pair :
                                                                           ^
/usr/home/me/libdynd/include/dynd/func/arrfunc.hpp:1378:32: note: in instantiation of member function 'dynd::nd::arithmetic_operator<dynd::nd::add,
      add_kernel, 2>::make' requested here
      static arrfunc self = T::make();
                               ^
/usr/home/me/libdynd/include/dynd/func/arrfunc.hpp:1396:14: note: in instantiation of member function 'dynd::nd::declfunc<dynd::nd::add>::get_self'
      requested here
      return get_self()(std::forward<A>(a)...);
             ^
/usr/home/me/libdynd/src/dynd/func/arithmetic.cpp:23:13: note: in instantiation of function template specialization
      'dynd::nd::declfunc<dynd::nd::add>::operator()<const dynd::nd::array &, const dynd::nd::array &>' requested here
  return add(a0, a1);
            ^
/usr/home/me/libdynd/include/dynd/type_sequence.hpp:367:10: note: template is declared here
  struct get_impl;
         ^
1 error generated.

AFAICT, this is some sort of incompatibility with an older version of libc++. I threw together a VM with a development version of FreeBSD 11.0, which has a more recent libc++ (version 3.4), and it builds fine. I'm not sure if this could cause versions on any versions of mac OSX, but it is still something to be aware of. The solution on the FreeBSD side is probably just to wait until FreeBSD 11.0 is released.

**Comment by izaid** [comment]
So I've never seen this is before. I'd vote towards an incompatibility as well.

**Comment by insertinterestingnamehere** [comment]
This has been fixed now.
