### ISSUE TITLE
Build error with gcc 4.8 and 5.1

### ISSUE THREAD

**Issue by insertinterestingnamehere** [libdynd/libdynd#418]
I first noticed this with my MinGW build, but it appears to depend primarily on the gcc version used.
Basically there are a bunch of "may be uninitialized" warnings that get translated into errors. Here's the error from gcc 5.1. It should be relatively easy to set up a Travis build for these versions of gcc if we want.

    /usr/bin/c++    -O3 -std=c++11 -fomit-frame-pointer -fstrict-aliasing -Wall -Wextra -Werror -Wno-missing-field-initializers -fPIC -fmax-errors=20 -Wno-type-limits -I/home/owner/libdynd/thirdparty/datetime/include -I/home/owner/libdynd/include -I/home/owner/libdynd/thirdparty/utf8/source -I/home/owner/libdynd/gcc51_build/include    -o CMakeFiles/libdynd_OBJ.dir/src/dynd/kernels/assignment_kernels.cpp.o -c /home/owner/libdynd/src/dynd/kernels/assignment_kernels.cpp
    In file included from /home/owner/libdynd/include/dynd/config.hpp:688:0,
                     from /home/owner/libdynd/include/dynd/types/base_type.hpp:11,
                     from /home/owner/libdynd/include/dynd/type.hpp:11,
                     from /home/owner/libdynd/src/dynd/kernels/assignment_kernels.cpp:6:
    /home/owner/libdynd/include/dynd/float16.hpp: In member function ‘void dynd::nd::assignment_kernel<DstTypeID, (dynd::type_kind_t)3u, Src0TypeID, (dynd::type_kind_t)3u, (dynd::assign_error_mode)1u>::single(char*, char* const*) [with dynd::type_id_t DstTypeID = (dynd::type_id_t)12u; dynd::type_id_t Src0TypeID = (dynd::type_id_t)12u]’:
    /home/owner/libdynd/include/dynd/float16.hpp:155:36: error: ‘<anonymous>.dynd::float16::m_bits’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
         return halfbits_to_float(m_bits);
                                        ^
    In file included from /home/owner/libdynd/src/dynd/kernels/assignment_kernels.cpp:7:0:
    /home/owner/libdynd/include/dynd/kernels/assignment_kernels.hpp:958:69: note: ‘<anonymous>’ was declared here
           if (isfinite(sd) && (sd < -std::numeric_limits<dst_type>::max() ||
                                                                         ^
    In file included from /home/owner/libdynd/include/dynd/config.hpp:688:0,
                     from /home/owner/libdynd/include/dynd/types/base_type.hpp:11,
                     from /home/owner/libdynd/include/dynd/type.hpp:11,
                     from /home/owner/libdynd/src/dynd/kernels/assignment_kernels.cpp:6:
    /home/owner/libdynd/include/dynd/float16.hpp: In member function ‘void dynd::nd::assignment_kernel<DstTypeID, (dynd::type_kind_t)3u, Src0TypeID, (dynd::type_kind_t)3u, (dynd::assign_error_mode)3u>::single(char*, char* const*) [with dynd::type_id_t DstTypeID = (dynd::type_id_t)12u; dynd::type_id_t Src0TypeID = (dynd::type_id_t)12u]’:
    /home/owner/libdynd/include/dynd/float16.hpp:155:36: error: ‘<anonymous>.dynd::float16::m_bits’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
         return halfbits_to_float(m_bits);
                                        ^
    In file included from /home/owner/libdynd/src/dynd/kernels/assignment_kernels.cpp:7:0:
    /home/owner/libdynd/include/dynd/kernels/assignment_kernels.hpp:1007:67: note: ‘<anonymous>’ was declared here
           if (isfinite(s) && (s < -std::numeric_limits<dst_type>::max() ||
                                                                       ^
    In file included from /home/owner/libdynd/include/dynd/config.hpp:688:0,
                     from /home/owner/libdynd/include/dynd/types/base_type.hpp:11,
                     from /home/owner/libdynd/include/dynd/type.hpp:11,
                     from /home/owner/libdynd/src/dynd/kernels/assignment_kernels.cpp:6:
    /home/owner/libdynd/include/dynd/float16.hpp: In member function ‘void dynd::nd::assignment_kernel<DstTypeID, (dynd::type_kind_t)3u, Src0TypeID, (dynd::type_kind_t)3u, (dynd::assign_error_mode)1u>::single(char*, char* const*) [with dynd::type_id_t DstTypeID = (dynd::type_id_t)12u; dynd::type_id_t Src0TypeID = (dynd::type_id_t)13u]’:
    /home/owner/libdynd/include/dynd/float16.hpp:155:36: error: ‘<anonymous>.dynd::float16::m_bits’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
         return halfbits_to_float(m_bits);
                                        ^
    In file included from /home/owner/libdynd/src/dynd/kernels/assignment_kernels.cpp:7:0:
    /home/owner/libdynd/include/dynd/kernels/assignment_kernels.hpp:958:69: note: ‘<anonymous>’ was declared here
           if (isfinite(sd) && (sd < -std::numeric_limits<dst_type>::max() ||
                                                                         ^
    In file included from /home/owner/libdynd/include/dynd/config.hpp:688:0,
                     from /home/owner/libdynd/include/dynd/types/base_type.hpp:11,
                     from /home/owner/libdynd/include/dynd/type.hpp:11,
                     from /home/owner/libdynd/src/dynd/kernels/assignment_kernels.cpp:6:
    /home/owner/libdynd/include/dynd/float16.hpp: In member function ‘void dynd::nd::assignment_kernel<DstTypeID, (dynd::type_kind_t)3u, Src0TypeID, (dynd::type_kind_t)3u, (dynd::assign_error_mode)3u>::single(char*, char* const*) [with dynd::type_id_t DstTypeID = (dynd::type_id_t)12u; dynd::type_id_t Src0TypeID = (dynd::type_id_t)13u]’:
    /home/owner/libdynd/include/dynd/float16.hpp:155:36: error: ‘<anonymous>.dynd::float16::m_bits’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
         return halfbits_to_float(m_bits);
                                        ^
    In file included from /home/owner/libdynd/src/dynd/kernels/assignment_kernels.cpp:7:0:
    /home/owner/libdynd/include/dynd/kernels/assignment_kernels.hpp:1007:67: note: ‘<anonymous>’ was declared here
           if (isfinite(s) && (s < -std::numeric_limits<dst_type>::max() ||
                                                                       ^
    In file included from /home/owner/libdynd/include/dynd/config.hpp:688:0,
                     from /home/owner/libdynd/include/dynd/types/base_type.hpp:11,
                     from /home/owner/libdynd/include/dynd/type.hpp:11,
                     from /home/owner/libdynd/src/dynd/kernels/assignment_kernels.cpp:6:
    /home/owner/libdynd/include/dynd/float16.hpp: In member function ‘void dynd::nd::assignment_kernel<DstTypeID, (dynd::type_kind_t)3u, Src0TypeID, (dynd::type_kind_t)3u, (dynd::assign_error_mode)1u>::single(char*, char* const*) [with dynd::type_id_t DstTypeID = (dynd::type_id_t)12u; dynd::type_id_t Src0TypeID = (dynd::type_id_t)14u]’:
    /home/owner/libdynd/include/dynd/float16.hpp:155:36: error: ‘<anonymous>.dynd::float16::m_bits’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
         return halfbits_to_float(m_bits);
                                        ^
    In file included from /home/owner/libdynd/src/dynd/kernels/assignment_kernels.cpp:7:0:
    /home/owner/libdynd/include/dynd/kernels/assignment_kernels.hpp:958:69: note: ‘<anonymous>’ was declared here
           if (isfinite(sd) && (sd < -std::numeric_limits<dst_type>::max() ||
                                                                         ^
    In file included from /home/owner/libdynd/include/dynd/config.hpp:688:0,
                     from /home/owner/libdynd/include/dynd/types/base_type.hpp:11,
                     from /home/owner/libdynd/include/dynd/type.hpp:11,
                     from /home/owner/libdynd/src/dynd/kernels/assignment_kernels.cpp:6:
    /home/owner/libdynd/include/dynd/float16.hpp: In member function ‘void dynd::nd::assignment_kernel<DstTypeID, (dynd::type_kind_t)3u, Src0TypeID, (dynd::type_kind_t)3u, (dynd::assign_error_mode)3u>::single(char*, char* const*) [with dynd::type_id_t DstTypeID = (dynd::type_id_t)12u; dynd::type_id_t Src0TypeID = (dynd::type_id_t)14u]’:
    /home/owner/libdynd/include/dynd/float16.hpp:155:36: error: ‘<anonymous>.dynd::float16::m_bits’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
         return halfbits_to_float(m_bits);
                                        ^
    In file included from /home/owner/libdynd/src/dynd/kernels/assignment_kernels.cpp:7:0:
    /home/owner/libdynd/include/dynd/kernels/assignment_kernels.hpp:1007:67: note: ‘<anonymous>’ was declared here
           if (isfinite(s) && (s < -std::numeric_limits<dst_type>::max() ||
                                                                       ^
    In file included from /home/owner/libdynd/include/dynd/config.hpp:688:0,
                     from /home/owner/libdynd/include/dynd/types/base_type.hpp:11,
                     from /home/owner/libdynd/include/dynd/type.hpp:11,
                     from /home/owner/libdynd/src/dynd/kernels/assignment_kernels.cpp:6:
    /home/owner/libdynd/include/dynd/float16.hpp: In member function ‘void dynd::nd::assignment_kernel<DstTypeID, (dynd::type_kind_t)3u, Src0TypeID, (dynd::type_kind_t)4u, (dynd::assign_error_mode)1u>::single(char*, char* const*) [with dynd::type_id_t DstTypeID = (dynd::type_id_t)12u; dynd::type_id_t Src0TypeID = (dynd::type_id_t)16u]’:
    /home/owner/libdynd/include/dynd/float16.hpp:155:36: error: ‘<anonymous>.dynd::float16::m_bits’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
         return halfbits_to_float(m_bits);
                                        ^
    In file included from /home/owner/libdynd/src/dynd/kernels/assignment_kernels.cpp:7:0:
    /home/owner/libdynd/include/dynd/kernels/assignment_kernels.hpp:1393:58: note: ‘<anonymous>’ was declared here
           if (s.real() < -std::numeric_limits<dst_type>::max() ||
                                                              ^
    In file included from /home/owner/libdynd/include/dynd/config.hpp:688:0,
                     from /home/owner/libdynd/include/dynd/types/base_type.hpp:11,
                     from /home/owner/libdynd/include/dynd/type.hpp:11,
                     from /home/owner/libdynd/src/dynd/kernels/assignment_kernels.cpp:6:
    /home/owner/libdynd/include/dynd/float16.hpp: In member function ‘void dynd::nd::assignment_kernel<DstTypeID, (dynd::type_kind_t)3u, Src0TypeID, (dynd::type_kind_t)4u, (dynd::assign_error_mode)1u>::single(char*, char* const*) [with dynd::type_id_t DstTypeID = (dynd::type_id_t)12u; dynd::type_id_t Src0TypeID = (dynd::type_id_t)17u]’:
    /home/owner/libdynd/include/dynd/float16.hpp:155:36: error: ‘<anonymous>.dynd::float16::m_bits’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
         return halfbits_to_float(m_bits);
                                        ^
    In file included from /home/owner/libdynd/src/dynd/kernels/assignment_kernels.cpp:7:0:
    /home/owner/libdynd/include/dynd/kernels/assignment_kernels.hpp:1393:58: note: ‘<anonymous>’ was declared here
           if (s.real() < -std::numeric_limits<dst_type>::max() ||
                                                              ^
    cc1plus: all warnings being treated as errors
    make[2]: *** [CMakeFiles/libdynd_OBJ.dir/src/dynd/kernels/assignment_kernels.cpp.o] Error 1
    make[2]: Leaving directory `/home/owner/libdynd/gcc51_build'
    make[1]: *** [CMakeFiles/libdynd_OBJ.dir/all] Error 2
    make[1]: Leaving directory `/home/owner/libdynd/gcc51_build'
    make: *** [all] Error 2

**Comment by insertinterestingnamehere** [comment]
I'm seeing this with gcc 4.9.2 as well now.

**Comment by izaid** [comment]
Okay, this is on my todo list to sort out. If you are trying to build dynd-python, it is currently broken (fixing that now).

**Comment by insertinterestingnamehere** [comment]
Thanks. There's no major rush on my end. I've been suppressing the error in all the builds where it has been cropping up. I've put these here primarily to document these though, since we should probably be able to install from source on all recent versions of gcc without having to override any flags.

**Comment by insertinterestingnamehere** [comment]
Also, thanks for the great work over the last few days. Something you did recently fixed the last few test failures I was seeing with my mingw-w64 dynd-python build.

**Comment by insertinterestingnamehere** [comment]
This one is also resolved by https://github.com/libdynd/libdynd/pull/452.
