### ISSUE TITLE
gcc 5.1 build error

### ISSUE THREAD

**Issue by insertinterestingnamehere** [libdynd/libdynd#443]
This is a new build error from converting warnings to errors with gcc-5.1. Setting the flags so that it warns instead of fails on the "maybe-uninitialized" warning is currently a usable workaround. Here's the log:

    /home/owner/libdynd/src/dynd/types/expr_type.cpp: In static member function ‘static void dynd::nd::base_kernel<T, 0u, -1, CKP>::strided_wrapper(char*, intptr_t, char* const*, const intptr_t*, size_t, dynd::ckernel_prefix*) [with T = {anonymous}::expr_type_offset_applier_extra<2>; CKP = dynd::ckernel_prefix; intptr_t = long int; size_t = long unsigned int]’:
    /home/owner/libdynd/src/dynd/types/expr_type.cpp:235:32: error: ‘*((void*)& src_copy +8)’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
           src_modified[i] = src[i] + offsets[i];
                                    ^
    In file included from /home/owner/libdynd/include/dynd/kernels/expr_kernel_generator.hpp:12:0,
                     from /home/owner/libdynd/include/dynd/types/expr_type.hpp:10,
                     from /home/owner/libdynd/src/dynd/types/expr_type.cpp:6:
    /home/owner/libdynd/include/dynd/kernels/base_kernel.hpp:246:13: note: ‘*((void*)& src_copy +8)’ was declared here
           char *src_copy[N];                                                       \
                 ^
    /home/owner/libdynd/include/dynd/kernels/base_kernel.hpp:258:3: note: in expansion of macro ‘BASE_KERNEL’
       BASE_KERNEL(kernel_request_host);
       ^
    /home/owner/libdynd/src/dynd/types/expr_type.cpp: In static member function ‘static void dynd::nd::base_kernel<T, 0u, -1, CKP>::strided_wrapper(char*, intptr_t, char* const*, const intptr_t*, size_t, dynd::ckernel_prefix*) [with T = {anonymous}::expr_type_offset_applier_extra<3>; CKP = dynd::ckernel_prefix; intptr_t = long int; size_t = long unsigned int]’:
    /home/owner/libdynd/src/dynd/types/expr_type.cpp:235:32: error: ‘*((void*)& src_copy +8)’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
           src_modified[i] = src[i] + offsets[i];
                                    ^
    In file included from /home/owner/libdynd/include/dynd/kernels/expr_kernel_generator.hpp:12:0,
                     from /home/owner/libdynd/include/dynd/types/expr_type.hpp:10,
                     from /home/owner/libdynd/src/dynd/types/expr_type.cpp:6:
    /home/owner/libdynd/include/dynd/kernels/base_kernel.hpp:246:13: note: ‘*((void*)& src_copy +8)’ was declared here
           char *src_copy[N];                                                       \
                 ^
    /home/owner/libdynd/include/dynd/kernels/base_kernel.hpp:258:3: note: in expansion of macro ‘BASE_KERNEL’
       BASE_KERNEL(kernel_request_host);
       ^
    /home/owner/libdynd/src/dynd/types/expr_type.cpp:235:32: error: ‘*((void*)& src_copy +16)’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
           src_modified[i] = src[i] + offsets[i];
                                    ^
    In file included from /home/owner/libdynd/include/dynd/kernels/expr_kernel_generator.hpp:12:0,
                     from /home/owner/libdynd/include/dynd/types/expr_type.hpp:10,
                     from /home/owner/libdynd/src/dynd/types/expr_type.cpp:6:
    /home/owner/libdynd/include/dynd/kernels/base_kernel.hpp:246:13: note: ‘*((void*)& src_copy +16)’ was declared here
           char *src_copy[N];                                                       \
                 ^
    /home/owner/libdynd/include/dynd/kernels/base_kernel.hpp:258:3: note: in expansion of macro ‘BASE_KERNEL’
       BASE_KERNEL(kernel_request_host);
       ^
    /home/owner/libdynd/src/dynd/types/expr_type.cpp: In static member function ‘static void dynd::nd::base_kernel<T, 0u, -1, CKP>::strided_wrapper(char*, intptr_t, char* const*, const intptr_t*, size_t, dynd::ckernel_prefix*) [with T = {anonymous}::expr_type_offset_applier_extra<4>; CKP = dynd::ckernel_prefix; intptr_t = long int; size_t = long unsigned int]’:
    /home/owner/libdynd/src/dynd/types/expr_type.cpp:235:32: error: ‘*((void*)& src_copy +8)’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
           src_modified[i] = src[i] + offsets[i];
                                    ^
    In file included from /home/owner/libdynd/include/dynd/kernels/expr_kernel_generator.hpp:12:0,
                     from /home/owner/libdynd/include/dynd/types/expr_type.hpp:10,
                     from /home/owner/libdynd/src/dynd/types/expr_type.cpp:6:
    /home/owner/libdynd/include/dynd/kernels/base_kernel.hpp:246:13: note: ‘*((void*)& src_copy +8)’ was declared here
           char *src_copy[N];                                                       \
                 ^
    /home/owner/libdynd/include/dynd/kernels/base_kernel.hpp:258:3: note: in expansion of macro ‘BASE_KERNEL’
       BASE_KERNEL(kernel_request_host);
       ^
    /home/owner/libdynd/src/dynd/types/expr_type.cpp:235:32: error: ‘*((void*)& src_copy +16)’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
           src_modified[i] = src[i] + offsets[i];
                                    ^
    In file included from /home/owner/libdynd/include/dynd/kernels/expr_kernel_generator.hpp:12:0,
                     from /home/owner/libdynd/include/dynd/types/expr_type.hpp:10,
                     from /home/owner/libdynd/src/dynd/types/expr_type.cpp:6:
    /home/owner/libdynd/include/dynd/kernels/base_kernel.hpp:246:13: note: ‘*((void*)& src_copy +16)’ was declared here
           char *src_copy[N];                                                       \
                 ^
    /home/owner/libdynd/include/dynd/kernels/base_kernel.hpp:258:3: note: in expansion of macro ‘BASE_KERNEL’
       BASE_KERNEL(kernel_request_host);
       ^
    /home/owner/libdynd/src/dynd/types/expr_type.cpp:235:32: error: ‘*((void*)& src_copy +24)’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
           src_modified[i] = src[i] + offsets[i];
                                    ^
    In file included from /home/owner/libdynd/include/dynd/kernels/expr_kernel_generator.hpp:12:0,
                     from /home/owner/libdynd/include/dynd/types/expr_type.hpp:10,
                     from /home/owner/libdynd/src/dynd/types/expr_type.cpp:6:
    /home/owner/libdynd/include/dynd/kernels/base_kernel.hpp:246:13: note: ‘*((void*)& src_copy +24)’ was declared here
           char *src_copy[N];                                                       \
                 ^
    /home/owner/libdynd/include/dynd/kernels/base_kernel.hpp:258:3: note: in expansion of macro ‘BASE_KERNEL’
       BASE_KERNEL(kernel_request_host);
       ^
    cc1plus: all warnings being treated as errors
    make[2]: *** [CMakeFiles/libdynd_OBJ.dir/src/dynd/types/expr_type.cpp.o] Error 1
    make[2]: Leaving directory `/home/owner/libdynd/gcc51_build'
    make[1]: *** [CMakeFiles/libdynd_OBJ.dir/all] Error 2
    make[1]: Leaving directory `/home/owner/libdynd/gcc51_build'
    make: *** [all] Error 2

**Comment by izaid** [comment]
If the "maybe unused" variables are arguments, there is a DYND_IGNORE_UNUSED(...) macro that fixes it. We can probably come up with something similar for declared variables.

**Comment by insertinterestingnamehere** [comment]
Yes, we could do the same thing for uninitialized variables. I'll look into this a little deeper on Monday and see if I can figure out if this is just compiler noise that we can safely ignore in all cases.

**Comment by insertinterestingnamehere** [comment]
Closed by https://github.com/libdynd/libdynd/pull/452.
