### ISSUE TITLE
gcc 5.1 linker error

### ISSUE THREAD

**Issue by insertinterestingnamehere** [libdynd/libdynd#467]
When compiling the tests with the latest master I'm getting a strange linker error.

    Linking CXX executable test_libdynd
    cd /home/owner/libdynd/gcc51_build/tests && /usr/bin/cmake -E cmake_link_script CMakeFiles/test_libdynd.dir/link.txt --verbose=1
    /usr/bin/g++-5   -Wno-error=maybe-uninitialized -O3 -std=c++11 -fomit-frame-pointer -fstrict-aliasing -Wall -Wextra -Werror -Wno-missing-field-initializers -fPIC -fmax-errors=20 -Wno-type-limits -DGTEST_USE_OWN_TR1_TUPLE=1 -O0 -O3 -DNDEBUG    CMakeFiles/test_libdynd.dir/pp/test_pp_arithmetic.cpp.o CMakeFiles/test_libdynd.dir/pp/test_pp_comparison.cpp.o CMakeFiles/test_libdynd.dir/pp/test_pp_if.cpp.o CMakeFiles/test_libdynd.dir/pp/test_pp_list.cpp.o CMakeFiles/test_libdynd.dir/pp/test_pp_logical.cpp.o CMakeFiles/test_libdynd.dir/pp/test_pp_token.cpp.o CMakeFiles/test_libdynd.dir/types/test_align_type.cpp.o CMakeFiles/test_libdynd.dir/types/test_bytes_type.cpp.o CMakeFiles/test_libdynd.dir/types/test_byteswap_type.cpp.o CMakeFiles/test_libdynd.dir/types/test_c_contiguous_type.cpp.o CMakeFiles/test_libdynd.dir/types/test_categorical_kind_type.cpp.o CMakeFiles/test_libdynd.dir/types/test_categorical_type.cpp.o CMakeFiles/test_libdynd.dir/types/test_complex_type.cpp.o CMakeFiles/test_libdynd.dir/types/test_convert_type.cpp.o CMakeFiles/test_libdynd.dir/types/test_char_type.cpp.o CMakeFiles/test_libdynd.dir/types/test_cuda_host_type.cpp.o CMakeFiles/test_libdynd.dir/types/test_cuda_device_type.cpp.o CMakeFiles/test_libdynd.dir/types/test_datashape_formatter.cpp.o CMakeFiles/test_libdynd.dir/types/test_datashape_parser.cpp.o CMakeFiles/test_libdynd.dir/types/test_date_type.cpp.o CMakeFiles/test_libdynd.dir/types/test_datetime_type.cpp.o CMakeFiles/test_libdynd.dir/types/test_fixed_dim_type.cpp.o CMakeFiles/test_libdynd.dir/types/test_fixed_bytes_kind_type.cpp.o CMakeFiles/test_libdynd.dir/types/test_fixed_bytes_type.cpp.o CMakeFiles/test_libdynd.dir/types/test_fixed_string_kind_type.cpp.o CMakeFiles/test_libdynd.dir/types/test_fixed_string_type.cpp.o CMakeFiles/test_libdynd.dir/types/test_groupby_type.cpp.o CMakeFiles/test_libdynd.dir/types/test_json_type.cpp.o CMakeFiles/test_libdynd.dir/types/test_option_type.cpp.o CMakeFiles/test_libdynd.dir/types/test_pointer_type.cpp.o CMakeFiles/test_libdynd.dir/types/test_string_type.cpp.o CMakeFiles/test_libdynd.dir/types/test_struct_type.cpp.o CMakeFiles/test_libdynd.dir/types/test_symbolic_types.cpp.o CMakeFiles/test_libdynd.dir/types/test_time_type.cpp.o CMakeFiles/test_libdynd.dir/types/test_tuple_type.cpp.o CMakeFiles/test_libdynd.dir/types/test_type.cpp.o CMakeFiles/test_libdynd.dir/types/test_type_type.cpp.o CMakeFiles/test_libdynd.dir/types/test_type_assign.cpp.o CMakeFiles/test_libdynd.dir/types/test_type_casting.cpp.o CMakeFiles/test_libdynd.dir/types/test_type_substitute.cpp.o CMakeFiles/test_libdynd.dir/types/test_type_pattern_match.cpp.o CMakeFiles/test_libdynd.dir/types/test_type_promotion.cpp.o CMakeFiles/test_libdynd.dir/types/test_var_dim_type.cpp.o CMakeFiles/test_libdynd.dir/func/test_apply.cpp.o CMakeFiles/test_libdynd.dir/func/test_arithmetic.cpp.o CMakeFiles/test_libdynd.dir/func/test_callable.cpp.o CMakeFiles/test_libdynd.dir/func/test_chain.cpp.o CMakeFiles/test_libdynd.dir/func/test_comparison.cpp.o CMakeFiles/test_libdynd.dir/func/test_elwise.cpp.o CMakeFiles/test_libdynd.dir/func/test_fft.cpp.o CMakeFiles/test_libdynd.dir/func/test_math.cpp.o CMakeFiles/test_libdynd.dir/func/test_multidispatch.cpp.o CMakeFiles/test_libdynd.dir/func/test_neighborhood.cpp.o CMakeFiles/test_libdynd.dir/func/test_outer.cpp.o CMakeFiles/test_libdynd.dir/func/test_permute.cpp.o CMakeFiles/test_libdynd.dir/func/test_random.cpp.o CMakeFiles/test_libdynd.dir/func/test_reduction.cpp.o CMakeFiles/test_libdynd.dir/func/test_registry.cpp.o CMakeFiles/test_libdynd.dir/func/test_rolling.cpp.o CMakeFiles/test_libdynd.dir/func/test_special.cpp.o CMakeFiles/test_libdynd.dir/func/test_take.cpp.o CMakeFiles/test_libdynd.dir/func/test_take_by_pointer.cpp.o CMakeFiles/test_libdynd.dir/gfunc/test_callable.cpp.o CMakeFiles/test_libdynd.dir/array/test_array.cpp.o CMakeFiles/test_libdynd.dir/array/test_array_range.cpp.o CMakeFiles/test_libdynd.dir/array/test_array_assign.cpp.o CMakeFiles/test_libdynd.dir/array/test_array_at.cpp.o CMakeFiles/test_libdynd.dir/array/test_array_cast.cpp.o CMakeFiles/test_libdynd.dir/array/test_array_compare.cpp.o CMakeFiles/test_libdynd.dir/array/test_array_views.cpp.o CMakeFiles/test_libdynd.dir/array/test_asarray.cpp.o CMakeFiles/test_libdynd.dir/array/test_arrmeta_holder.cpp.o CMakeFiles/test_libdynd.dir/array/test_json_formatter.cpp.o CMakeFiles/test_libdynd.dir/array/test_json_parser.cpp.o CMakeFiles/test_libdynd.dir/array/test_memmap.cpp.o CMakeFiles/test_libdynd.dir/array/test_view.cpp.o CMakeFiles/test_libdynd.dir/array/test_with.cpp.o CMakeFiles/test_libdynd.dir/test_bool1.cpp.o CMakeFiles/test_libdynd.dir/test_config.cpp.o CMakeFiles/test_libdynd.dir/test_float16.cpp.o CMakeFiles/test_libdynd.dir/test_integer_sequence.cpp.o CMakeFiles/test_libdynd.dir/test_iterator.cpp.o CMakeFiles/test_libdynd.dir/test_shape_tools.cpp.o CMakeFiles/test_libdynd.dir/test_type_sequence.cpp.o CMakeFiles/test_libdynd.dir/test_platform.cpp.o CMakeFiles/test_libdynd.dir/__/thirdparty/gtest/gtest-all.cc.o CMakeFiles/test_libdynd.dir/__/thirdparty/gtest/gtest_main.cc.o  -o test_libdynd -rdynamic ../libdynd.so -lpthread ../thirdparty/cephes/libcephes.a ../thirdparty/datetime/libdatetime.a -Wl,-rpath,/home/owner/libdynd/gcc51_build: 
    CMakeFiles/test_libdynd.dir/types/test_time_type.cpp.o: In function `TimeDType_Properties_Test::TestBody()':
    test_time_type.cpp:(.text+0x370b): undefined reference to `dynd::nd::array::f(char const*)'
    collect2: error: ld returned 1 exit status
    make[2]: *** [tests/test_libdynd] Error 1
    make[2]: Leaving directory `/home/owner/libdynd/gcc51_build'
    make[1]: *** [tests/CMakeFiles/test_libdynd.dir/all] Error 2
    make[1]: Leaving directory `/home/owner/libdynd/gcc51_build'
    make: *** [all] Error 2
    gcc51_build.sh: 7: gcc51_build.sh: ./tests/test_libdynd: not found

This shows up when using the Debian gcc 5.1 and when using mingw-w64. I've tried deleting the old installation directory and that doesn't fix the problem.
Any thoughts as to what could be causing this?

**Comment by izaid** [comment]
Yep, this one is easily solved. If you see undefined reference to "dynd::nd::array::f", it means some file is very likely missing an #include "dynd/gfunc/call_callable.hpp". gfunc is the ancient arrfunc which can't be deleted until we sort out views properly, it causes trouble sometimes. Try putting the include in test_time_type.cpp.

**Comment by insertinterestingnamehere** [comment]
Yep, that fixes it, I'll submit a PR shortly. Thanks!
